# MA2008B — Ejercicio en notebook  
## Machine Learning como problema de optimización: pérdidas y riesgo empírico

**Duración sugerida:** 30–40 minutos  
**Modalidad:** individual o equipos de 2–3 estudiantes  
**Producto:** matriz comparativa de pérdidas y justificación

### Objetivos del ejercicio

Al finalizar, el estudiante deberá poder:

1. Calcular errores de predicción.
2. Comparar MAE, MSE y RMSE.
3. Analizar el efecto de un outlier sobre distintas funciones de pérdida.
4. Calcular log loss y hinge loss en un ejemplo de clasificación.
5. Justificar qué pérdida usar según el problema.

## 1. Importar librerías

Ejecuta la siguiente celda.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option("display.precision", 4)

# Parte A — Regresión: comparación entre MAE, MSE y RMSE

Se tiene una variable real \(y_i\) y dos modelos predictivos: Modelo A y Modelo B.

El Modelo A predice bien la mayoría de observaciones, pero falla mucho en un punto extremo.  
El Modelo B comete errores moderados, pero más uniformes.

La pregunta central es:

> ¿Cuál modelo es mejor? La respuesta depende de la pérdida elegida.

In [ ]:
# Datos observados y predicciones de dos modelos

datos = pd.DataFrame({
    "observacion": [1, 2, 3, 4, 5],
    "y_real": [10, 12, 13, 15, 100],
    "y_hat_A": [11, 13, 14, 16, 80],
    "y_hat_B": [5, 7, 8, 10, 95]
})

datos

   observacion  y_real  y_hat_A  y_hat_B
0            1      10       11        5
1            2      12       13        7
2            3      13       14        8
3            4      15       16       10
4            5     100       80       95

## 2. Calcular errores

Recuerda:

\[
e_i = y_i - \hat{y}_i
\]

Calcula los errores de ambos modelos.

In [ ]:
# TODO: calcula los errores de ambos modelos

datos["error_A"] = None
datos["error_B"] = None

datos

   observacion  y_real  y_hat_A  y_hat_B error_A error_B
0            1      10       11        5    None    None
1            2      12       13        7    None    None
2            3      13       14        8    None    None
3            4      15       16       10    None    None
4            5     100       80       95    None    None

## 3. Implementar funciones de pérdida para regresión

Completa las siguientes funciones:

\[
MAE = \frac{1}{n}\sum_{i=1}^n |y_i-\hat{y}_i|
\]

\[
MSE = \frac{1}{n}\sum_{i=1}^n (y_i-\hat{y}_i)^2
\]

\[
RMSE = \sqrt{MSE}
\]

In [ ]:
def mae(y, y_hat):
    """
    Calcula Mean Absolute Error.
    """
    # TODO: reemplaza pass por el cálculo correspondiente
    pass


def mse(y, y_hat):
    """
    Calcula Mean Squared Error.
    """
    # TODO: reemplaza pass por el cálculo correspondiente
    pass


def rmse(y, y_hat):
    """
    Calcula Root Mean Squared Error.
    """
    # TODO: reemplaza pass por el cálculo correspondiente
    pass

## 4. Evaluar ambos modelos

Usa tus funciones para comparar Modelo A y Modelo B.

In [ ]:
y = datos["y_real"].to_numpy()
y_hat_A = datos["y_hat_A"].to_numpy()
y_hat_B = datos["y_hat_B"].to_numpy()

resultados_regresion = pd.DataFrame({
    "modelo": ["A", "B"],
    "MAE": [mae(y, y_hat_A), mae(y, y_hat_B)],
    "MSE": [mse(y, y_hat_A), mse(y, y_hat_B)],
    "RMSE": [rmse(y, y_hat_A), rmse(y, y_hat_B)]
})

resultados_regresion

## 5. Visualizar el efecto del outlier

Ejecuta la siguiente celda y observa cómo el punto extremo afecta a cada modelo.

In [ ]:
plt.figure(figsize=(8, 5))
plt.plot(datos["observacion"], datos["y_real"], marker="o", label="Real")
plt.plot(datos["observacion"], datos["y_hat_A"], marker="o", label="Modelo A")
plt.plot(datos["observacion"], datos["y_hat_B"], marker="o", label="Modelo B")
plt.xlabel("Observación")
plt.ylabel("Valor")
plt.title("Comparación de predicciones")
plt.legend()
plt.grid(True)
plt.show()

## 6. Preguntas de análisis

Responde en una celda de markdown debajo:

1. ¿Cuál modelo tiene menor MAE?
2. ¿Cuál modelo tiene menor MSE?
3. ¿Cuál modelo tiene menor RMSE?
4. ¿Por qué MSE y RMSE reaccionan distinto que MAE?
5. Si el valor 100 fuera un error de captura, ¿qué modelo preferirías?
6. Si el valor 100 fuera un evento real importante, ¿qué modelo preferirías?

In [ ]:
# Escribe aquí tus respuestas como comentarios o agrega una celda Markdown debajo.

# 1.
# 2.
# 3.
# 4.
# 5.
# 6.

# Parte B — Riesgo empírico

El riesgo empírico es el promedio de las pérdidas sobre el conjunto de entrenamiento:

\[
R_{\text{emp}}(\theta)=\frac{1}{n}\sum_{i=1}^{n}L(y_i,f(x_i;\theta))
\]

En esta parte se calculará el riesgo empírico usando pérdida cuadrática.

In [ ]:
def riesgo_empirico_mse(y, y_hat):
    """
    Calcula el riesgo empírico usando pérdida cuadrática.
    En este caso coincide con MSE.
    """
    # TODO: implementa el cálculo
    pass

riesgo_A = riesgo_empirico_mse(y, y_hat_A)
riesgo_B = riesgo_empirico_mse(y, y_hat_B)

print("Riesgo empírico MSE - Modelo A:", riesgo_A)
print("Riesgo empírico MSE - Modelo B:", riesgo_B)

## Pregunta

Según el riesgo empírico con pérdida cuadrática:

> ¿Qué modelo seleccionaría el proceso de optimización?

In [ ]:
# Respuesta:

# Parte C — Clasificación: log loss

Ahora considera un problema de clasificación binaria:

\[
y_i \in \{0,1\}
\]

El modelo no produce directamente una clase, sino una probabilidad estimada:

\[
\hat{p}_i = P(y_i=1|x_i)
\]

La log loss para clasificación binaria es:

\[
L(y,\hat{p}) =
-
\left[
y\log(\hat{p}) + (1-y)\log(1-\hat{p})
\right]
\]

In [ ]:
clasificacion = pd.DataFrame({
    "observacion": [1, 2, 3, 4, 5, 6],
    "y_real": [1, 0, 1, 1, 0, 0],
    "p_hat_modelo_1": [0.90, 0.20, 0.80, 0.55, 0.30, 0.10],
    "p_hat_modelo_2": [0.60, 0.40, 0.99, 0.01, 0.20, 0.30]
})

clasificacion

## 7. Implementar log loss

Precaución numérica: si \(\hat{p}\) es exactamente 0 o 1, el logaritmo puede causar problemas.  
Por eso se recorta la probabilidad con un valor pequeño \(\epsilon\).

In [ ]:
def log_loss_binaria(y, p_hat, eps=1e-15):
    """
    Calcula log loss binaria promedio.
    """
    y = np.array(y)
    p_hat = np.array(p_hat)

    # Evitar log(0)
    p_hat = np.clip(p_hat, eps, 1 - eps)

    # TODO: implementa la fórmula de log loss
    pass

In [ ]:
y_clf = clasificacion["y_real"].to_numpy()
p1 = clasificacion["p_hat_modelo_1"].to_numpy()
p2 = clasificacion["p_hat_modelo_2"].to_numpy()

resultados_log_loss = pd.DataFrame({
    "modelo": ["Modelo 1", "Modelo 2"],
    "log_loss": [
        log_loss_binaria(y_clf, p1),
        log_loss_binaria(y_clf, p2)
    ]
})

resultados_log_loss

## 8. Preguntas de análisis sobre log loss

Responde:

1. ¿Cuál modelo tiene menor log loss?
2. Observa la cuarta observación. El valor real es \(y=1\), pero el Modelo 2 predice \(\hat{p}=0.01\). ¿Qué efecto tiene esto?
3. ¿Por qué log loss castiga fuertemente la sobreconfianza incorrecta?

In [ ]:
# Respuestas:
# 1.
# 2.
# 3.

# Parte D — Clasificación por margen: hinge loss

La hinge loss se usa frecuentemente en clasificadores tipo SVM.

Para etiquetas:

\[
y_i \in \{-1,1\}
\]

y puntaje del modelo \(s_i\), la pérdida es:

\[
L(y_i,s_i)=\max(0,1-y_i s_i)
\]

Si \(y_i s_i \geq 1\), el punto está correctamente clasificado con margen suficiente y la pérdida es cero.

In [ ]:
margen = pd.DataFrame({
    "observacion": [1, 2, 3, 4, 5],
    "y_real": [1, 1, -1, -1, 1],
    "score_modelo": [2.0, 0.4, -1.5, 0.2, -0.8]
})

margen

## 9. Implementar hinge loss

In [ ]:
def hinge_loss(y, score):
    """
    Calcula la hinge loss promedio.
    """
    y = np.array(y)
    score = np.array(score)

    # TODO: implementa max(0, 1 - y*score)
    pass

perdida_hinge = hinge_loss(
    margen["y_real"].to_numpy(),
    margen["score_modelo"].to_numpy()
)

print("Hinge loss promedio:", perdida_hinge)

In [ ]:
# Opcional: calcular pérdida por observación para interpretar cada caso.

margen["producto_y_score"] = margen["y_real"] * margen["score_modelo"]
margen["hinge_individual"] = None  # TODO: calcula la pérdida individual

margen

## 10. Preguntas de análisis sobre hinge loss

1. ¿Qué observaciones tienen pérdida cero?
2. ¿Qué observaciones están mal clasificadas?
3. ¿Qué observaciones están bien clasificadas pero no tienen margen suficiente?
4. ¿Por qué hinge loss no se interpreta como probabilidad?

In [ ]:
# Respuestas:
# 1.
# 2.
# 3.
# 4.

# Parte E — Producto final

Completa la siguiente matriz comparativa.

| Pérdida | Tipo de problema | Fórmula | Ventaja | Desventaja | Sensibilidad a outliers | ¿Cuándo usarla? |
|---|---|---|---|---|---|---|
| MSE | | | | | | |
| MAE | | | | | | |
| RMSE | | | | | | |
| Log loss | | | | | | |
| Hinge loss | | | | | | |

Después responde:

> En un problema donde hay datos atípicos por errores de captura, ¿qué pérdida usarías y por qué?

> En un problema donde los errores grandes son muy costosos, ¿qué pérdida usarías y por qué?

> En un problema de clasificación donde necesitas probabilidades bien calibradas, ¿qué pérdida usarías y por qué?

In [ ]:
# Espacio para construir la matriz comparativa en Python, si se desea.

matriz = pd.DataFrame({
    "Pérdida": ["MSE", "MAE", "RMSE", "Log loss", "Hinge loss"],
    "Tipo de problema": ["", "", "", "", ""],
    "Fórmula": ["", "", "", "", ""],
    "Ventaja": ["", "", "", "", ""],
    "Desventaja": ["", "", "", "", ""],
    "Sensibilidad a outliers": ["", "", "", "", ""],
    "Cuándo usarla": ["", "", "", "", ""]
})

matriz

,Pérdida,Tipo de problema,Fórmula,Ventaja,Desventaja,Sensibilidad a outliers,Cuándo usarla
0,MSE,,,,,,
1,MAE,,,,,,
2,RMSE,,,,,,
3,Log loss,,,,,,
4,Hinge loss,,,,,,